# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest
# Set Up Project
steps:
- script: |
    echo "Starting Pipeline Execution."
  # Run Docker container with mount and run tests
    docker --version \
    docker run -i \
    -u 0:0 \
    -e ACCEPT_EULA=true \
    -v "$(pwd)/temp:/temp" \
    lavanya93/parabank-baseline:2022 /bin/bash -c " \
    
    docker ps \
    echo -e "\nDebug -- Verify ./temp contents\n"
    ls -R $(pwd)/temp
  displayName: Run Tests
  env:
    pwd: $(Build.Repository.LocalPath)
  
- publish: /home/vsts/work/1/s/temp
  artifact: TSA
# Publish Test Results

- task: PublishParasoftTestResults@1